version: '3.8'

services:
  news-write-db:
    image: mysql:8.0
    container_name: the-news-mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  news-cache:
    image: redis:alpine
    container_name: the-news-redis-cache
    ports:
      - "6379:6379"

  nginx-lb:
    image: nginx:latest
    container_name: the-news-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data: